### ISSUE TITLE
Apache Reverse Proxy Configuration

### ISSUE THREAD

**Issue by gbear605** [spantaleev/matrix-docker-ansible-deploy#121]
I'm trying to configure my server to have Apache running simultaneously with Matrix, using the information from https://github.com/spantaleev/matrix-docker-ansible-deploy/tree/master/examples/apache. 

I started with Apache 2.4.18 running successfully on a Ubuntu 16.04.5 server.

I took the example conf files (matrix-riot-web.conf and matrix-synapse.conf), replaced the occurrences of DOMAIN with my domain name, and placed them in /etc/apache2/sites-enabled. When I try to start Apache, it says:

```
AH00526: Syntax error on line 11 of /etc/apache2/sites-enabled/matrix-riot-web.conf:
ProxyRequests not allowed here
```

Any advice for what to do differently?

**Comment by spantaleev** [comment]
It's probably the `ProxyRequests Off` directive in `<Location /.well-known/acme-challenge>` for the `<VirtualHost *:80> vhosts.

As far as I can see in the [ProxyRequests](https://httpd.apache.org/docs/2.4/mod/mod_proxy.html#proxyrequests) documentation, `ProxyRequests` is only allowed in the server config or in a virtual host config, not in `Location` directives.

You can try removing it manually and that should fix it.

If you find other problems or suggestions, I'd be happy to hear from you so we can improve the example Apache configs.. Or you can make a Pull Request as well!

**Comment by gbear605** [comment]
I wound up having to comment out the ProxyRequests and ProxyVia line, and I removed TLSv1.3 as an option for the SSLProxyProtocol.

I now seem to have that working. I'm still having a few issues though with getting my server working. When I run the self test (`ansible-playbook -i inventory/hosts setup.yml --tags=self-check`), it fails with:

```
TASK [matrix-synapse : Check Matrix Client API] **********************************************************************************************************************************************************************************************
fatal: [matrix.greenwichmeanti.me -> 127.0.0.1]: FAILED! => {"changed": false, "content": "", "msg": "Status code was -1 and not [200]: Request failed: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1051)>", "redirected": false, "status": -1, "url": "https://matrix.greenwichmeanti.me/_matrix/client/versions"}
...ignoring

TASK [matrix-synapse : Fail if Matrix Client API not working] ********************************************************************************************************************************************************************************
fatal: [matrix.greenwichmeanti.me -> 127.0.0.1]: FAILED! => {"changed": false, "msg": "Failed checking Matrix Client API is up at `matrix.greenwichmeanti.me` (checked endpoint: `https://matrix.greenwichmeanti.me/_matrix/client/versions`). Is Synapse running? Is port 443 open in your firewall? Full error: {'content': '', 'redirected': False, 'url': 'https://matrix.greenwichmeanti.me/_matrix/client/versions', 'msg': 'Status code was -1 and not [200]: Request failed: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1051)>', 'status': -1, 'failed': True, 'changed': False}"}
```

When I go to the relevant URL though (https://matrix.greenwichmeanti.me/_matrix/client/versions), it seems to be fine.

**Comment by gbear605** [comment]
Also, I'm not sure how to set up Dimension with this. I'd guess that it can be mostly similar to the one for Riot, but I'm not sure what the port that it passes through should be.

**Comment by spantaleev** [comment]
I've made some fixes in d18fe3610f9 (sans the TLSv1.3 thing -- we'd better leave that there for people whose Apache supports it).

I've added a sample Dimension configuration in 8660cd421.
As you've guessed, it should be the same as the one for Riot, but going to `127.0.0.1:8184`.

**Comment by spantaleev** [comment]
I'll close this now. Your input has been quite valuable in improving the example configuration for Apache! Thank you! :+1: 

If you have other feedback or trouble, feel free to re-open this or start a new issue!
